import { FastifyInstance } from "fastify";
import { configureServer } from "@/server.js";
import { beforeEach, describe, expect, it } from "vitest";
import { waitForMessageJob } from "../../helpers/wait-for-message-job.js";

describe("POST /api/messages", () => {
    let server: FastifyInstance;

    beforeEach(async () => {
        server = await configureServer();

        return async () => {
            await server.close();
        };
    });

    it("should enqueue a message and persist it through the worker", async () => {
        const response = await server.inject({
            method: "POST",
            url: "/api/messages",
            body: {
                text: "Hello, world!",
            },
        });

        const { statusCode } = response;
        const json = response.json();

        expect(statusCode).toBe(202);
        expect(json.data.jobId).toEqual(expect.any(String));

        await waitForMessageJob({ server, jobId: json.data.jobId });

        const list = await server.inject({
            method: "GET",
            url: "/api/messages",
        });

        expect(list.json()).toMatchObject({
            data: {
                messages: [
                    {
                        id: json.data.id,
                        createdAt: expect.any(String),
                        text: "Hello, world!",
                    },
                ],
            },
        });
    });

    it("should reject a message with missing text", async () => {
        const response = await server.inject({
            method: "POST",
            url: "/api/messages",
            body: {
                // Missing text property
            },
        });

        const { statusCode } = response;
        const json = response.json();

        expect(statusCode).toBe(400);
        expect(json).toHaveProperty("error");
    });

    it("should not insert a duplicate when the same create job runs twice", async () => {
        const messageService = server.di.resolve("messageService");

        const payload = {
            id: await server.di.resolve("messageRepository").generateId(),
            text: "Hello once",
            enqueuedAt: new Date(),
        };

        const first = await messageService.createMessage(payload);
        const second = await messageService.createMessage(payload);

        expect(second.id).toBe(first.id);

        expect(
            await server.prisma.message.count({
                where: { id: payload.id },
            })
        ).toBe(1);
    });

    it("should persist the message under a client-provided UUID v7 id", async () => {
        const id = "019a0000-0000-7000-8000-0000000000a1";

        const response = await server.inject({
            method: "POST",
            url: "/api/messages",
            body: { id, text: "Client id" },
        });

        expect(response.statusCode).toBe(202);
        expect(response.json().data.id).toBe(id);

        await waitForMessageJob({ server, jobId: response.json().data.jobId });

        const stored = await server.prisma.message.findUniqueOrThrow({
            where: { id },
        });

        expect(stored.text).toBe("Client id");
    });

    it("should reject a client-provided id that is not a UUID v7", async () => {
        const response = await server.inject({
            method: "POST",
            url: "/api/messages",
            body: { id: "6f1c1f0e-8a4b-4c3e-9d2a-1b2c3d4e5f60", text: "v4 id" },
        });

        expect(response.statusCode).toBe(400);
    });

    it("should default the id to a UUID v7 generated by Postgres", async () => {
        const message = await server.prisma.message.create({
            data: { text: "Default id" },
        });

        expect(message.id).toMatch(
            /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
        );
    });
});
