services:
    postgresdb:
        image: postgres:16.4
        container_name: test-postgres-db
        restart: no
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "12345"
        ports:
            - "5432:5432"
        expose:
            - "5432"
        volumes:
            - "./.volumes/test-postgresql:/var/lib/postgresql/data"
