services:
    postgresdb:
        image: postgres:16.4
        container_name: test-postgres-db
        restart: no
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "12345"
        ports:
            - "5433:5432"
        expose:
            - "5433"
        volumes:
            - "./.volumes/test-postgresql:/var/lib/postgresql/data"

    gcp-storage:
        image: fsouza/fake-gcs-server:1.52.2
        container_name: test-gcp-storage
        restart: no
        command: -scheme http -public-host localhost:4443 -port 4443
        ports:
            - "4443:4443"
        expose:
            - "4443"
        volumes:
            - "./.volumes/test-gcp-storage:/data"

    aws-s3:
        image: localstack/localstack
        container_name: test-aws-s3
        restart: no
        environment:
            SERVICES: "s3"
            AWS_DEFAULT_REGION: "us-east-1"
            AWS_S3_BUCKET_NAME: "test-bucket"
        ports:
            - "4566:4566"
        expose:
            - "4566"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./scripts/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"
