export const BULLMQ_CONNECT_TIMEOUT_MS = 2000;

export const BULLMQ_KEEP_ALIVE_MS = 10000;

export const BULLMQ_MAX_RETRIES_PER_REQUEST = null;

export const BULLMQ_RETRY_BACKOFF_STEP_MS = 200;

export const BULLMQ_RETRY_BACKOFF_MAX_MS = 2000;
